// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEshop.Data;

#nullable disable

namespace MyEshop.Migrations
{
    [DbContext(typeof(MyEshopContext))]
    partial class MyEshopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyEshop.Models.Categoritoproduct", b =>
                {
                    b.Property<int>("productid")
                        .HasColumnType("int");

                    b.Property<int>("categoriid")
                        .HasColumnType("int");

                    b.Property<int>("categorycsId")
                        .HasColumnType("int");

                    b.Property<int>("productcsId")
                        .HasColumnType("int");

                    b.HasKey("productid", "categoriid");

                    b.HasIndex("categorycsId");

                    b.HasIndex("productcsId");

                    b.ToTable("categoritoproducts");
                });

            modelBuilder.Entity("MyEshop.Models.Productcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemid")
                        .HasColumnType("int");

                    b.Property<int>("numbers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("itemid")
                        .IsUnique();

                    b.ToTable("productcs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "فلفل دلمه ای نیز فلفل شیرین و یا کپسایسیم هستند و در رنگ های مختلف مثل زرد، قرمز، سبز، بنفش و نارنجی موجود هستند. این سبزیجات ، بیش از 900 سال پیش در جنوب و آمریکای مرکزی پرورش داده شدند و نام فلفل را از استعمارگران اروپایی آمریکای شمالی دریافت کردند.\r\n\r\n",
                            Name = "فلفل دلمه ای",
                            itemid = 1,
                            numbers = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = " توت فرنگی دارای مقدار قابل توجهی آنتی اکسیدان است و حتی دارای مزایای قلبی عروقی می باشد. لوبیا سبز ،منبع غنی از چربی های امگا 3 است. کاروتنوئید و فلاونوئید موجود در لوبیا سبز ،دارای مزایای ضد التهابی هستند.",
                            Name = "توت فرنگی",
                            itemid = 2,
                            numbers = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "لوبیا سبز، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " لوبیا سبز",
                            itemid = 3,
                            numbers = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "کلم بنفش، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " کلم بنفش ",
                            itemid = 4,
                            numbers = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "گوجه فرنگی، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " گوجه  فرنگی",
                            itemid = 5,
                            numbers = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "کلم بروکلی، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " کلم بروکلی",
                            itemid = 6,
                            numbers = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = " هویج، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " هویج",
                            itemid = 7,
                            numbers = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "ابمیوه های طبیعی، سرشار از ویتامین C است. این ویتامین هم نوع دیگری از آنتی‌اکسیدان‌ها است. به همین دلیل مصرف کلم می‌تواند نیاز بدن به این ویتامین مهم را تأمین کند.",
                            Name = " ابمیوه های طبیعی",
                            itemid = 8,
                            numbers = 0
                        });
                });

            modelBuilder.Entity("MyEshop.Models.Users", b =>
                {
                    b.Property<int>("userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userid"));

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Registerdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userid");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MyEshop.Models.categorycs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categorycs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "سبزیجات",
                            Name = "سبزیحات"
                        },
                        new
                        {
                            Id = 2,
                            Description = " میوه جات",
                            Name = "میوه جات"
                        },
                        new
                        {
                            Id = 3,
                            Description = "لبنیات",
                            Name = "لبنیات"
                        });
                });

            modelBuilder.Entity("MyEshop.Models.item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quentitystock")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quentitystock = 0,
                            price = 854.0m
                        },
                        new
                        {
                            Id = 2,
                            Quentitystock = 0,
                            price = 3302.0m
                        },
                        new
                        {
                            Id = 3,
                            Quentitystock = 0,
                            price = 2500m
                        },
                        new
                        {
                            Id = 4,
                            Quentitystock = 0,
                            price = 140000m
                        },
                        new
                        {
                            Id = 5,
                            Quentitystock = 0,
                            price = 250000m
                        },
                        new
                        {
                            Id = 6,
                            Quentitystock = 0,
                            price = 68000m
                        },
                        new
                        {
                            Id = 7,
                            Quentitystock = 0,
                            price = 48000m
                        },
                        new
                        {
                            Id = 8,
                            Quentitystock = 0,
                            price = 64000m
                        });
                });

            modelBuilder.Entity("MyEshop.Models.Categoritoproduct", b =>
                {
                    b.HasOne("MyEshop.Models.categorycs", "categorycs")
                        .WithMany("categoritoproducts")
                        .HasForeignKey("categorycsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyEshop.Models.Productcs", "productcs")
                        .WithMany("categotitoProducts")
                        .HasForeignKey("productcsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorycs");

                    b.Navigation("productcs");
                });

            modelBuilder.Entity("MyEshop.Models.Productcs", b =>
                {
                    b.HasOne("MyEshop.Models.item", "item")
                        .WithOne("productcs")
                        .HasForeignKey("MyEshop.Models.Productcs", "itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("MyEshop.Models.Productcs", b =>
                {
                    b.Navigation("categotitoProducts");
                });

            modelBuilder.Entity("MyEshop.Models.categorycs", b =>
                {
                    b.Navigation("categoritoproducts");
                });

            modelBuilder.Entity("MyEshop.Models.item", b =>
                {
                    b.Navigation("productcs")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
